### ISSUE TITLE
"open-meteo: data refresh failed" for Ukraine

### ISSUE THREAD

**Issue by ghdotc** [breezy-weather/breezy-weather#471]
### Steps to reproduce

Idk if it's app issue or open-meteo itself. I'm sorry if I'm not suppoused to open issue here.

1. Add any ukrainian city or village
2. Try to load data

### Expected behavior

Data for ukrainian city or village should load

### Actual behavior

Data for ukraninan city or village failes to load
![1000013024](https://github.com/breezy-weather/breezy-weather/assets/142530731/e8610072-967a-43ac-bf00-65710be8237f)

### Weather source used

open-meteo

### Breezy Weather version

4.6.6-beta

### Android version

Android 13

### Device

Xiaomi Poco F3, Redmi Note 8T,  Redmi 6A

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.6 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Open-Meteo bug, tracked here: open-meteo/open-meteo#437
Thank you for reporting!

**Comment by papjul** [comment]
Fixed upstream

**Comment by ghdotc** [comment]
> Fixed upstream

But I still have this issue. Although, this link works:
https://api.open-meteo.com/v1/forecast?timezone=auto&timeformat=unixtime&latitude=50.45465850830078&longitude=30.523799896240234&daily=temperature_2m_max

**Comment by papjul** [comment]
Ah yeah, it worked a few minutes ago, and now no longer. Let's have a look again tomorrow, in case of some caching issue.

**Comment by papjul** [comment]
So, it is fixed on forecast, but not on air quality.
Waiting for a fix upstream.

**Comment by papjul** [comment]
Works now
