### ISSUE TITLE
Display daily and hourly trend edits not taking effect 

### ISSUE THREAD

**Issue by NBA613** [breezy-weather/breezy-weather#81]
### Steps to reproduce

Remove or change the order of display hourly or daily trend.
Changes do not take effect.

### Expected behavior

Display should follow the user's edits.

### Actual behavior

Display keeps default order and still shows removed trends. 
Additionally, under hourly trend, once air quality is removed it no longer shows on bottom to be re-added. 
Screenshot missing air quality:
![Screenshot_20230626-022606](https://github.com/breezy-weather/breezy-weather/assets/110447969/62084e20-3614-4181-a844-f28fb2812c37)

### Weather provider used

Any

### Breezy Weather version

4.0.3-Alpha

### Android version

Android 13

### Device

Pixel 6 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
Fixed with edf8a9d9ff2ed493333bccb3977e9e6a4e65846e

**Comment by NBA613** [comment]
> Fixed with [edf8a9d](https://github.com/breezy-weather/breezy-weather/commit/edf8a9d9ff2ed493333bccb3977e9e6a4e65846e)

Not sure if you noticed, but I also mentioned that Air quality can not be re-added once it has been removed from hourly trend (screenshot above). Still an issue in 4.0.4 Alpha. Should I open a new issue?

**Comment by papjul** [comment]
> > Fixed with [edf8a9d](https://github.com/breezy-weather/breezy-weather/commit/edf8a9d9ff2ed493333bccb3977e9e6a4e65846e)
> 
> Not sure if you noticed, but I also mentioned that Air quality can not be re-added once it has been removed from hourly trend (screenshot above). Still an issue in 4.0.4 Alpha. Should I open a new issue?

Saw it, thought I fixed it
